### ISSUE TITLE
Not all experiments appear to be getting counted.

### ISSUE THREAD

**Issue by joshtoper** [splitrb/split#337]
I've got a Split experiment set up which starts on a given page which all users land on after registering on my site. I'm using Redis as the store.

In my development and staging environments, you can see in the Split console that everyone is being added; however in my production environment it only appears to be counting perhaps one in every five registrations.

My staging and production environments are incredibly similar; both on Heroku, both using RedisToGo, yet they seem to be behaving differently. 

This is a really tricky one, as I'm unable to reproduce it in my development environment; has anyone encountered anything like this before?

It's worth noting that I've conducted a Split experiment on my site before with total success; I have not changed any configurations since that experiment, which only ended earlier this week.

**Comment by jpstevens** [comment]
+1 for this, not sure why...

**Comment by nwallace** [comment]
I had a similar issue. Using Redis for persistence. First experiment went as expected, but second experiment looked like nothing was happening.

It turned out that it was due to the fact that every user for that experiment was being "excluded" from the test.  When choosing the alternative to deliver for the split test, my users hit [this line in Split::Trial#choose!](https://github.com/splitrb/split/blob/ffe35d66210661382ab5da75603d55875f3ade2a/lib/split/trial.rb#L64) and that returned true, which automatically sent all users to the control group and skipped the part where it counts them as participants in the split test.

Digging into it revealed that they were all excluded because `max_experiments_reached?` was returning true. This was unexpected because we ended our first experiment two weeks ago, but the `keys_without_experiments` method was returning a list containing my first experiment. Thus, my users were considered as "current participants" in that experiment, even though we ended it a long time ago.

We thought that deleting that first experiment would fix the issue, but we still had `keys_without_experiments` returning a list with that first experiment name in it.

**The fix we ended up going with was to configure `config.allow_multiple_experiments = true`.** This solved our issues and now the second experiment is up and running.

I'm speculating here, but I wonder if something is going wrong when you end and/or delete an experiment that's persisted in Redis. It seems like `max_experiments_reached?` should not consider experiments that have been ended or deleted.

**Comment by andreibondarev** [comment]
I've issued a pull request to fix this issue: https://github.com/splitrb/split/pull/373

**Comment by andrew** [comment]
I've just merged @andreibondarev's pull request related to this, can someone try it out and see if it helps?

**Comment by andrew** [comment]
Closing as this issue it's over a year old, please reopen if it's still affecting you.
