### ISSUE TITLE
Private ab_test method used in split_cacheable

### ISSUE THREAD

**Issue by irubnich** [splitrb/split#361]
Hey there,

I'm a maintainer of the `split_cacheable` gem (https://github.com/harrystech/split_cacheable).

We're just about to resolve this issue that you opened last year: https://github.com/harrystech/split_cacheable/issues/2

We use the `ab_test` method, which has been made private as of v1.1 of Split. We're wondering whether the method can be made public since we hook into it.

Thanks!

**Comment by andrew** [comment]
@irubnich I seem to remember making that method private because it's included in ApplicationController [here](https://github.com/splitrb/split/blob/38cac58d438a5ebe85f3ea21f396f2e276394098/lib/split/engine.rb#L6) and we didn't want that to be accidentally exposed as an action if users have catch all style routes in rails like `/:controller/:action` but it's been quite a while since that change was made and it might no longer be relevant, what do you think?

**Comment by irubnich** [comment]
For us it's more a matter of being uncomfortable with hooking into a private API. But if you're comfortable with the method being called from a controller anyway then I think it's okay for it to be public.

I do see your point about the routing conflict though. Maybe the method can be namespaced?

**Comment by andrew** [comment]
If you can work out a way to namespace it without breaking backwards compatibility then I'm all for it, otherwise I'm very sure it won't be changing as it would break every users setup!

**Comment by andrew** [comment]
Closing as this issue it's over a year old, please reopen if it's still affecting you.
