### ISSUE TITLE
Q: How to get the bucket of  `combined_experiments` ?

### ISSUE THREAD

**Issue by cmantas** [splitrb/split#500]
When you, eg.
```ruby
  Split.configuration.experiments = {
        :button_color_experiment => {
          :alternatives => ["blue", "green"],
          :combined_experiments => ["button_color_on_signup", "button_color_on_login"]
        }
      }

thing =  ab_combined_test(:button_color_experiment)
```
After you run `ab_combined_test` how can you know whether you are in the `blue` or `green` bucket (and decide what color to actually draw the button) ?
In this snippet, `thing` gets the value of `["button_color_on_signup", "button_color_on_login"]
`, which is actually the result of the `each` method [here](https://github.com/splitrb/split/blob/master/lib/split/combined_experiments_helper.rb#L9)

**Comment by semanticart** [comment]
It looks like this should be just a matter of returning `alternative` after this block: https://github.com/splitrb/split/blob/87fbd830fe2804094655a1e43ada4d9ebfa0ded6/lib/split/combined_experiments_helper.rb#L9-L20

That + a test is a pretty quick PR.

Unfortunately from my usage, it doesn't look like `ab_combined_test` works properly. Using `ab_combined_test` locally will generate the first combined experiment in the `combined_experiments` array properly but will generate new versions of subsequent experiments for each participant.

So in your example, you'd get a consistent test for `button_color_on_signup` but each participant in `button_color_on_login` would cause the version for that test to bump.

It isn't immediately clear to me and it is certainly possible I'm doing something wrong but I don't see what that would be.

Maybe @daviddening has some thoughts on the functionality since he originally wrote it?

**Comment by semanticart** [comment]
Aha. the issue is line 18 above. Only the selected alternative is passed in (with weight of 1) but since not all alternatives are represented, it appears to be a new test and the version is bumped.

I'll try to get a PR together to fix this.
