### ISSUE TITLE
How do I delete all Split related data in Redis?

### ISSUE THREAD

**Issue by NielsKSchjoedt** [splitrb/split#641]
I want to remove the gem, I used a redis instance/db that contain other data too. I wanna delete all data related to split. How do I do that?

**Comment by andrehjr** [comment]
Hi there,

You can also remove experiments configs by calling `Split::ExperimentCatalog.all.each(&:delete)`.

Otherwise, If you used a namespace when Redis was first configured, by following https://github.com/splitrb/split#namespaces. You just need to get all keys with that prefix and remove them.

if you used RedisAdapter for storing users, you can grep all keys starting with 'persistence' and removing them.
