### ISSUE TITLE
Error connecting to Redis with cookie config

### ISSUE THREAD

**Issue by ericalli** [splitrb/split#691]
I'm having trouble getting Split to work using the cookie adapter (and not Redis). 

**To Reproduce**
1. Add `gem 'split'` to gemfile and `bundle install`
2. Add `config/initializers/split.rb` file with the following configs:
```
Split.configure do |config|
  config.persistence = :cookie
  config.persistence_cookie_length = 2592000 # 30 days
end
```
3. Add an a/b test to a controller action:
`@ab_test = ab_test(:example_test, "control", "variant")`
4. Load the page in the browser and the following error appears:
`Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)`

<img width="1015" alt="Screen Shot 2022-06-26 at 4 05 56 PM" src="https://user-images.githubusercontent.com/13506/175837187-d0c7b20a-bf93-4b70-9eeb-0fd536908eba.png">

**Comment by andrehjr** [comment]
Hi! 🎉 

So, the issue here is that Split basically has two kinds of storage:
- Experiment Data: configurations for each experiment. This is used whenever ab_test is called and also powers the Web Interface / Dashboard.
   This needs Redis for storage. That's not configurable at the moment. So, you need a Redis instance here.
- User Data: The experiments and alternatives the user is associated with. This can be stored on either Cookies/Redis. Which is described here. https://github.com/splitrb/split#experiment-persistence.

As Split still needs Redis for it to work. And there are no plans to remove this dependency. I'll go ahead and close this issue.

If the Redis requirement(or the persistence-related stuff) is not clear on the README file, we could make it so. 🙌
